openapi: 3.0.1
info:
  title: Szampchat server api
  version: "0.1"
servers:
- url: http://localhost:8081/api
  description: Local server
paths:
  /channels/{channelId}:
    put:
      tags:
      - channel-controller
      operationId: editChannel
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Channel"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Channel"
    delete:
      tags:
      - channel-controller
      operationId: deleteChannel
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /users:
    post:
      tags:
      - user-controller
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
    delete:
      tags:
      - user-controller
      operationId: deleteUser
      responses:
        "200":
          description: OK
  /roles:
    post:
      tags:
      - role-controller
      operationId: createRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Role"
  /communities:
    get:
      tags:
      - Community
      operationId: getUserCommunities
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Community"
    post:
      tags:
      - Community
      operationId: createCommunity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommunityCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Community"
  /communities/{communityId}:
    get:
      tags:
      - Community
      summary: Get detailed info about community
      operationId: getCommunity
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Community"
        "404":
          description: Community by given ID was not found
    post:
      tags:
      - Community
      operationId: addMember
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CommunityMember"
    delete:
      tags:
      - Community
      operationId: deleteCommunity
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    patch:
      tags:
      - Community
      operationId: editCommunity
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Community"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Community"
  /communities/{communityId}/join:
    post:
      tags:
      - Community
      operationId: joinCommunity
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JoinRequestDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CommunityMember"
  /communities/{communityId}/invite:
    post:
      tags:
      - Community
      operationId: inviteToCommunity
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/InvitationResponseDTO"
  /channels:
    post:
      tags:
      - channel-controller
      operationId: createChannel
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChannelCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Channel"
  /channels/{channelId}/messages:
    get:
      tags:
      - message-controller
      summary: Get messages for given channel
      operationId: getMessages
      parameters:
      - name: channelId
        in: path
        description: Snowflake ID of text channel
        required: true
        schema:
          type: integer
          format: int64
        example: 20276884193411072
      - name: before
        in: query
        description: Get messages before this message Snowflake ID
        required: false
        schema:
          type: integer
          format: int64
        example: 21388369783160832
      - name: limit
        in: query
        description: Max number of messages
        required: false
        schema:
          type: integer
          format: int32
        example: 10
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MessageDTO"
    post:
      tags:
      - message-controller
      operationId: createMessage
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Message"
  /users/description:
    patch:
      tags:
      - user-controller
      operationId: editDescription
      parameters:
      - name: descriptionDTO
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/UserDescriptionDTO"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
  /users/avatar:
    patch:
      tags:
      - user-controller
      operationId: editAvatar
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
  /roles/{roleId}:
    get:
      tags:
      - role-controller
      operationId: getRole
      parameters:
      - name: roleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Role"
        "404":
          description: Role by given ID was not found
    delete:
      tags:
      - role-controller
      operationId: deleteRole
      parameters:
      - name: roleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    patch:
      tags:
      - role-controller
      operationId: editRole
      parameters:
      - name: roleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Role"
  /channels/{channelId}/messages/{messageId}:
    delete:
      tags:
      - message-controller
      operationId: deleteMessage
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: messageId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    patch:
      tags:
      - message-controller
      operationId: editMessage
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: messageId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EditMessageDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Message"
  /users/{userId}:
    get:
      tags:
      - user-controller
      operationId: getUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
  /users/me:
    get:
      tags:
      - user-controller
      operationId: getMe
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDTO"
  /communities/{communityId}/roles:
    get:
      tags:
      - role-controller
      operationId: getRolesForCommunity
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Role"
  /communities/{communityId}/members:
    get:
      tags:
      - Community
      operationId: getCommunityMembers
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CommunityMemberRolesDTO"
  /communities/{communityId}/info:
    get:
      tags:
      - Community
      operationId: getFullCommunityInfo
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FullCommunityInfoDTO"
  /communities/{communityId}/channels:
    get:
      tags:
      - channel-controller
      operationId: getChannelsForCommunity
      parameters:
      - name: communityId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ChannelDTO"
components:
  schemas:
    Channel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        communityId:
          type: integer
          format: int64
        type:
          type: string
          format: byte
    UserCreateDTO:
      type: object
      properties:
        username:
          type: string
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        imageUrl:
          type: string
        description:
          type: string
    RoleCreateDTO:
      type: object
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        permission:
          type: integer
          format: int64
        community:
          type: integer
          format: int64
    CommunityCreateDTO:
      type: object
      properties:
        name:
          type: string
    Community:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        ownerId:
          type: integer
          format: int64
        imageUrl:
          type: string
    CommunityMember:
      type: object
      properties:
        communityId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
    JoinRequestDTO:
      type: object
      properties:
        invitationId:
          type: integer
          format: int64
    InvitationResponseDTO:
      type: object
      properties:
        link:
          type: string
    ChannelCreateDTO:
      type: object
      properties:
        communityId:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum:
          - TEXT_CHANNEL
          - VOICE_CHANNEL
    MessageCreateDTO:
      type: object
      properties:
        text:
          type: string
        communityId:
          type: integer
          format: int64
        respondsToMessage:
          type: integer
          format: int64
        gifLink:
          type: string
    Message:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        updated_at:
          type: string
          format: date-time
        respondsToMessage:
          type: integer
          format: int64
        gifLink:
          type: string
        channelId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
    UserDescriptionDTO:
      type: object
      properties:
        description:
          type: string
    EditMessageDTO:
      type: object
      properties:
        text:
          type: string
    CommunityMemberRolesDTO:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/UserDTO"
        roles:
          uniqueItems: true
          type: array
          items:
            type: integer
            format: int64
    FullCommunityInfoDTO:
      type: object
      properties:
        community:
          $ref: "#/components/schemas/Community"
        channels:
          type: array
          items:
            $ref: "#/components/schemas/Channel"
        members:
          type: array
          items:
            $ref: "#/components/schemas/CommunityMemberRolesDTO"
        roles:
          type: array
          items:
            $ref: "#/components/schemas/Role"
    ChannelDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        community:
          type: integer
          format: int64
        type:
          type: integer
          format: int32
    MessageAttachmentDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        size:
          type: integer
          format: int32
        name:
          type: string
    MessageDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        updated_at:
          type: string
          format: date-time
        respondsToMessage:
          type: integer
          format: int64
        gifLink:
          type: string
        attachments:
          type: array
          items:
            $ref: "#/components/schemas/MessageAttachmentDTO"
        reactions:
          type: array
          items:
            $ref: "#/components/schemas/ReactionPreviewDTO"
        channelId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
    ReactionPreviewDTO:
      type: object
      properties:
        emoji:
          type: string
        count:
          type: integer
          format: int32
        me:
          type: boolean
