version: '3.9'

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=chat
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080