version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=chat
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ~/apps/pgadmin:/var/lib/pgadmin
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - "8082:8080"
    command:
      - "start-dev"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ~/apps/rabbitmq:/var/lib/rabbitmq
      # TODO can't get it to work, maybe traeffik may help
      # using local server for now
  # livekit:
    # container_name: livekit
    # image: livekit/livekit-server:v1.8
    # ports:
    #   - 7880:7880
    #   - 7881:7881
    #   - 7882:7882/udp
    # entrypoint: "/livekit-server --dev --bind 0.0.0.0"
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/root/redis
      # - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
volumes:
  keycloak:
  redis:
  # add postgres volume here
  # and pgadmin