spring:
  application:
    name: szampchat-server
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chat
    username: root
    password: root
  data:
    rest:
      detection-strategy: annotated
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8082/realms/szampchat"
  main:
    web-application-type: reactive
  webflux:
    base-path: /api
  rsocket:
    server:
      port: 8083
      mapping-path: /events
      transport: websocket
  jackson:
    default-property-inclusion: NON_NULL
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
server:
  error:
    include-message: always
  port: 8081
springdoc:
  swagger-ui:
    path: /
app:
  livekit:
    url: "http://localhost:7880"
    key: devkey
    secret: secret
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org:
      springframework:
        security: TRACE