spring:
  application:
    name: szampchat-server
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chat
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      detection-strategy: annotated
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8082/realms/szampchat"
  main:
    web-application-type: reactive
  webflux:
    base-path: /api
  rsocket:
    server:
      port: 7000
      mapping-path: /rsocket  # Defines the RSocket mapping path
server:
  error:
    include-message: always
  port: 8081

logging:
  level:
    org:
      springframework:
        security: TRACE

