package com.szampchat.server.shared.docs;

public enum DocsProperties {
    RESPONSE_419,
    RESPONSE_401,
    REQUIRES_MEMBER_PERMISSION,
    REQUIRES_NOT_MEMBER_PERMISSION,
    REQUIRES_OWNER_PERMISSION,
    DOCUMENT_PATH_VARIABLES
}
