name: Build and test web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: web/package-lock.json
          node-version: 22
          cache: npm
          
      - name: Install dependencies
        working-directory: 'web'
        run: npm install
        
      - name: Run unit tests
        working-directory: 'web'
        run: npm run test
